const deps = require("./package.json").dependencies;

module.exports = {
  name: "thewebuiguy",
  exposes: {
    "./AccountDetailsLayout": "./src/components/AccountDetailsLayout",
    "./Alert": "./src/components/Alert",
    "./Button": "./src/components/Button",
    "./ButtonOutline": "./src/components/ButtonOutline",
    "./Checkbox": "./src/components/Checkbox",
    "./Dropdown": "./src/components/Dropdown",
    "./ExternalLink": "./src/components/ExternalLink",
    "./FourOhFour": "./src/components/FourOhFour",
    "./HomePageSectionTitle": "./src/components/HomePageSectionTitle",
    "./Input": "./src/components/Input",
    "./InputGroup": "./src/components/InputGroup",
    "./NoData": "./src/components/NoData",
    "./PageTitle": "./src/components/PageTitle",
    "./Pagination": "./src/components/Pagination",
    "./Pill": "./src/components/Pill",
    "./Radio": "./src/components/Radio",
    "./SearchInput": "./src/components/SearchInput",
    "./SectionTitle": "./src/components/SectionTitle",
    "./Select": "./src/components/Select",
    "./Stats": "./src/components/Stats",
    "./StatWithChange": "./src/components/StatWithChange",
    "./Table": "./src/components/Table",
    "./TableCell": "./src/components/TableCell",
    "./TableHeader": "./src/components/TableHeader",
    "./TableLoader": "./src/components/TableLoader",
    "./TableRow": "./src/components/TableRow",
    "./TableSortIndicator": "./src/components/TableSortIndicator",
    "./TableSortPill": "./src/components/TableSortPill",
    "./Tabs": "./src/components/Tabs",
    "./TextArea": "./src/components/TextArea",
    "./Toggle": "./src/components/Toggle",
  },
  remotes: {
  },
  filename: "remoteEntry.js",
  shared: {
    ...deps,
    react: {
      singleton: true,
      requiredVersion: deps["react"],
    },
    "react-dom": {
      singleton: true,
      requiredVersion: deps["react-dom"],
    },
  },
};